apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-mongo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KaouechHaythem/spring-mongo-k8s-components.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
    automated:
      selfHeal: true 
      prune: true 
